# Generated by Django 4.0 on 2022-09-17 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=200)),
                ('store_id', models.CharField(max_length=200)),
                ('store_name', models.CharField(max_length=200)),
                ('store_type', models.CharField(max_length=200)),
                ('store_house_no', models.IntegerField(max_length=200)),
                ('store_land_mark', models.TextField(max_length=500)),
                ('store_street', models.TextField(max_length=500)),
                ('store_city', models.TextField(max_length=200)),
                ('store_pin_code', models.IntegerField(max_length=200)),
                ('store_GST_no', models.CharField(max_length=200)),
                ('store_EST_no', models.CharField(max_length=200)),
                ('selling_mode', models.CharField(max_length=200)),
                ('rules', models.TextField(max_length=200)),
                ('store_template', models.CharField(max_length=200)),
                ('store_business_email', models.CharField(max_length=200)),
                ('store_contact_no', models.IntegerField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.CharField(max_length=200)),
                ('store_name', models.CharField(max_length=200)),
                ('store_type', models.CharField(max_length=200)),
                ('store_house_no', models.IntegerField(max_length=200)),
                ('store_land_mark', models.TextField(max_length=200)),
                ('store_street', models.TextField(max_length=200)),
                ('store_city', models.TextField(max_length=200)),
                ('store_pin_code', models.IntegerField(max_length=200)),
                ('store_latitude', models.CharField(max_length=200)),
                ('store_longitude', models.CharField(max_length=200)),
                ('store_Online_status', models.CharField(max_length=200)),
                ('store_Offline_status', models.CharField(max_length=200)),
                ('opening_time', models.DateTimeField(max_length=200)),
                ('closing_time', models.DateTimeField(max_length=200)),
                ('deliverable_distance', models.CharField(max_length=200)),
                ('delivery_time', models.DateTimeField(max_length=200)),
                ('delivery_cost', models.IntegerField(max_length=200)),
                ('store_upi_id', models.CharField(max_length=200)),
            ],
        ),
    ]
