# Generated by Django 4.0 on 2022-09-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedetails',
            name='store_contact_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='storedetails',
            name='store_house_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='storedetails',
            name='store_pin_code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='delivery_cost',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='store_house_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='store_pin_code',
            field=models.IntegerField(),
        ),
    ]
