# Generated by Django 4.0 on 2022-09-16 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.TextField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=500)),
                ('description', models.TextField(max_length=1000)),
                ('client_type', models.CharField(max_length=200)),
                ('client_id', models.TextField(max_length=200)),
                ('store_id', models.TextField(max_length=200)),
                ('creation_time', models.DateTimeField(auto_now=True)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(max_length=100)),
                ('lock_status', models.BooleanField(default=False)),
                ('resolve_status', models.CharField(max_length=100)),
                ('resolve_time', models.DateTimeField()),
                ('resolve_date', models.DateField()),
                ('current_step', models.CharField(max_length=200)),
                ('active_support_agent', models.CharField(max_length=200)),
            ],
        ),
    ]
