# Generated by Django 4.0 on 2022-09-16 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='active_support_agent',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='client_id',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='current_step',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='resolve_status',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='store_id',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
