# Generated by Django 4.0 on 2022-09-16 10:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0002_alter_supportticket_active_support_agent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='creation_date',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='lock_status',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='resolve_date',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='resolve_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
