# Generated by Django 4.0 on 2022-09-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0004_alter_supportticket_creation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='active_support_agent',
            field=models.CharField(default='innpy-member', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='client_id',
            field=models.TextField(default='dde44iku', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='current_step',
            field=models.CharField(default='Processing', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='resolve_status',
            field=models.CharField(default='pending', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='status',
            field=models.CharField(default=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='store_id',
            field=models.TextField(default='yu86ji90k8', max_length=200, null=True),
        ),
    ]
